apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: alpine
        args:
          - sleep
          - infinity
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
          protocol: TCP
        #in the service type: LoadBalancer
