apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysqlport
  selector:
   app: mysql
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        args:
          - sleep
          - infinity
        #env:
        #- name: MYSQL_ROOT_PASSWORD
        #  valueFrom:
        #    secretKeyRef:
        #      name: mysql-pass
        #      key: password
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysqlport
        volumeMounts:
        - name: mysql-pstorage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pstorage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
