apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysqlport
  selector:
   app: mysql
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi
---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: mysql
#  namespace: default
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: mysql
#  template:
#    metadata:
#      labels:
#        app: mysql
#    spec:
#      containers:
#      - name: mysql
#        image: mysql
#        args:
#          - sleep
#          - infinity
#        imagePullPolicy: Never
#        ports:
#        - containerPort: 3306
#          name: mysqlport
#      volumes:
#      - name: mysql
#        persistentVolumeClaim:
#          claimName: mysql
#      restartPolicy: Always
#        volumeMounts:
#          - name: mysql
#          mountPath: /var/lib/mysql
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mysql
    labels:
      app: mysql
  spec:
    selector:
      matchLabels:
        app: mysql
    template:
      metadata:
        labels:
          app: mysql
      spec:
        containers:
        - name: mysql
          image: mysql
          args:
            - sleep
            - infinity
          imagePullPolicy: Never
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql
        volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql