kind: Pod
apiVersion: v1
metadata:
  name: alpine
  namespace: default
  selfLink: /api/v1/namespaces/default/pods/alpine
  uid: 896211fe-235d-460c-b005-3f185697ad23
  resourceVersion: '90621'
  creationTimestamp: '2020-12-27T18:44:06Z'
  labels:
    run: alpine
  managedFields:
    - manager: kubectl-run
      operation: Update
      apiVersion: v1
      time: '2020-12-27T18:44:06Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:run': {}
        'f:spec':
          'f:containers':
            'k:{"name":"alpine"}':
              .: {}
              'f:args': {}
              'f:image': {}
              'f:imagePullPolicy': {}
              'f:name': {}
              'f:ports':
                .: {}
                'k:{"containerPort":80,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:protocol': {}
              'f:resources': {}
              'f:terminationMessagePath': {}
              'f:terminationMessagePolicy': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2020-12-27T18:44:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"172.17.0.8"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
spec:
  volumes:
    - name: default-token-mxbrl
      secret:
        secretName: default-token-mxbrl
        defaultMode: 420
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - infinity
      ports:
        - containerPort: 80
          protocol: TCP
      resources: {}
      volumeMounts:
        - name: default-token-mxbrl
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: minikube
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-12-27T18:44:06Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-12-27T18:44:09Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-12-27T18:44:09Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-12-27T18:44:06Z'
  hostIP: 192.168.99.100
  podIP: 172.17.0.8
  podIPs:
    - ip: 172.17.0.8
  startTime: '2020-12-27T18:44:06Z'
  containerStatuses:
    - name: alpine
      state:
        running:
          startedAt: '2020-12-27T18:44:09Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: 'alpine:latest'
      imageID: >-
        docker-pullable://alpine@sha256:3c7497bf0c7af93428242d6176e8f7905f2201d8fc5861f45be7a346b5f23436
      containerID: >-
        docker://6d10d6be2c4e16a070906b9c5023c0e99f988b44e024c304d3b96b9fc0347832
      started: true
  qosClass: BestEffort
